#############################################################################
# Makefile for building: genepender
# Generated by qmake (3.0) (Qt 5.0.1) on: Mon Jun 17 18:44:49 2013
# Project:  genepender.pro
# Template: app
# Command: /opt/Qt5.0.1/5.0.1/gcc_64/bin/qmake -spec linux-g++-64 -o Makefile genepender.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/linux-g++-64 -I. -I/opt/Qt5.0.1/5.0.1/gcc_64/include -I/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1 -Wl,-rpath,/opt/Qt5.0.1/5.0.1/gcc_64 -Wl,-rpath,/opt/Qt5.0.1/5.0.1/gcc_64/lib
LIBS          = $(SUBLIBS) -L/opt/Qt5.0.1/5.0.1/gcc_64/lib -lQt5Core -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /opt/Qt5.0.1/5.0.1/gcc_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		pender.cpp 
OBJECTS       = main.o \
		pender.o
DIST          = /opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/common/shell-unix.conf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/common/unix.conf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/common/linux.conf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/common/g++-base.conf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/qconfig.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_bootstrap.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_clucene.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_designercomponents.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_platformsupport.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_quickparticles.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_v8.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/qt_config.prf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/linux-g++-64/qmake.conf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/spec_post.prf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/default_pre.prf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/unix/default_pre.prf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/release.prf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/default_post.prf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/shared.prf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/warn_on.prf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/qt.prf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/resources.prf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/moc.prf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/wayland-scanner.prf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/exceptions.prf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/yacc.prf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/lex.prf \
		genepender.pro \
		genepender.pro
QMAKE_TARGET  = genepender
DESTDIR       = 
TARGET        = genepender


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: genepender.pro /opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/linux-g++-64/qmake.conf /opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/common/shell-unix.conf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/common/unix.conf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/common/linux.conf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/common/g++-base.conf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/qconfig.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_bootstrap.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_clucene.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_designercomponents.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_platformsupport.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_quickparticles.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_v8.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/qt_config.prf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/linux-g++-64/qmake.conf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/spec_post.prf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/default_pre.prf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/unix/default_pre.prf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/release.prf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/default_post.prf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/shared.prf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/warn_on.prf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/qt.prf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/resources.prf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/moc.prf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/wayland-scanner.prf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/exceptions.prf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/yacc.prf \
		/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/lex.prf \
		genepender.pro \
		/opt/Qt5.0.1/5.0.1/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -spec linux-g++-64 -o Makefile genepender.pro
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/spec_pre.prf:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/common/shell-unix.conf:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/common/unix.conf:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/common/linux.conf:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/common/gcc-base.conf:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/common/gcc-base-unix.conf:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/common/g++-base.conf:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/common/g++-unix.conf:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/qconfig.pri:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_bootstrap.pri:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_clucene.pri:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_core.pri:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_designercomponents.pri:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_help.pri:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_network.pri:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_platformsupport.pri:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools.pri:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_quickparticles.pri:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_script.pri:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_v8.pri:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/qt_functions.prf:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/qt_config.prf:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/linux-g++-64/qmake.conf:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/spec_post.prf:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/exclusive_builds.prf:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/default_pre.prf:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/unix/default_pre.prf:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/release.prf:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/default_post.prf:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/shared.prf:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/warn_on.prf:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/qt.prf:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/resources.prf:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/moc.prf:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/unix/thread.prf:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/wayland-scanner.prf:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/testcase_targets.prf:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/exceptions.prf:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/yacc.prf:
/opt/Qt5.0.1/5.0.1/gcc_64/mkspecs/features/lex.prf:
genepender.pro:
/opt/Qt5.0.1/5.0.1/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++-64 -o Makefile genepender.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/genepender1.0.0 || $(MKDIR) .tmp/genepender1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/genepender1.0.0/ && $(COPY_FILE) --parents IntergenicOnly.h MapInterface.h InterAndExonic.h pender.h .tmp/genepender1.0.0/ && $(COPY_FILE) --parents main.cpp pender.cpp .tmp/genepender1.0.0/ && (cd `dirname .tmp/genepender1.0.0` && $(TAR) genepender1.0.0.tar genepender1.0.0 && $(COMPRESS) genepender1.0.0.tar) && $(MOVE) `dirname .tmp/genepender1.0.0`/genepender1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/genepender1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_wayland-server-header_make_all:
compiler_wayland-server-header_clean:
compiler_wayland-client-header_make_all:
compiler_wayland-client-header_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_wayland-code_make_all:
compiler_wayland-code_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp pender.h \
		MapInterface.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/QString \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qatomic_integrity.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qoldbasicatomic.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qatomic_vxworks.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qatomic_power.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qatomic_alpha.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qatomic_bfin.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qatomic_s390.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qatomic_sh4a.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qatomic_sparc.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/QMap \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/QTextStream \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/QStringList \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/QFile \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qfile.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qfiledevice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

pender.o: pender.cpp pender.h \
		MapInterface.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/QString \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qatomic_integrity.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qoldbasicatomic.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qatomic_vxworks.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qatomic_power.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qatomic_alpha.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qatomic_bfin.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qatomic_s390.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qatomic_sh4a.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qatomic_sparc.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/QMap \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/QTextStream \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/QStringList \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/QFile \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qfile.h \
		/opt/Qt5.0.1/5.0.1/gcc_64/include/QtCore/qfiledevice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pender.o pender.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

